In [9]:
!pip install yfinance pandas requests beautifulsoup4 plotly nbformat lxml

Requirement already satisfied: yfinance in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (1.3.0)
Requirement already satisfied: pandas in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: requests in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (4.14.3)
Requirement already satisfied: plotly in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (6.7.0)
Requirement already satisfied: nbformat in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (5.10.4)
Requirement already satisfied: lxml in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (6.1.0)
Requirement already satisfied: numpy>=1.16.5 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (2.4.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (2026.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (4.0.5)
Requirement already satisfied: curl_cffi>=0.15 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from plotly) (2.21.2)
Requirement already satisfied: packaging in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from plotly) (26.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from nbformat) (5.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: rich in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\majay\OneDrive\Desktop\JavaTest\Stock_Dashboard_Project\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [10]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [11]:
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [12]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

tables = pd.read_html(url)
tesla_revenue = tables[0]

tesla_revenue.columns = ["Date", "Revenue"]
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",", "")
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace("$", "")
tesla_revenue.dropna(inplace=True)
tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]
tesla_revenue.tail()

    Date Revenue
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112

In [13]:
gme = yf.Ticker("GME")
gme_data = gme.history(period="max")
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666417,1.666417,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [14]:
gme_revenue = pd.DataFrame({
    "Date": [
        "2020-12-31",
        "2021-01-31",
        "2021-04-30",
        "2021-07-31",
        "2021-10-31"
    ],
    "Revenue": [
        2124,
        2254,
        1277,
        1183,
        1297
    ]
})

gme_revenue.tail()

         Date  Revenue
0  2020-12-31     2124
1  2021-01-31     2254
2  2021-04-30     1277
3  2021-07-31     1183
4  2021-10-31     1297

In [15]:
def make_graph(stock_data, revenue_data, stock):

    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue"),
        vertical_spacing=0.3
    )

    stock_data = stock_data.copy()
    revenue_data = revenue_data.copy()

    stock_data["Date"] = pd.to_datetime(stock_data["Date"])
    revenue_data["Date"] = pd.to_datetime(revenue_data["Date"])

    fig.add_trace(
        go.Scatter(
            x=stock_data["Date"],
            y=stock_data["Close"],
            name="Share Price"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=revenue_data["Date"],
            y=revenue_data["Revenue"].astype(float),
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_layout(
        title=stock,
        showlegend=False,
        height=900
    )

    fig.show()

In [16]:
make_graph(tesla_data, tesla_revenue, "Tesla")

In [17]:
make_graph(gme_data, gme_revenue, "GameStop")